#!/usr/bin/env python

# Bionic Reading

import re
import sys

def bold(s):
    return '<b>' + s + '</b>'

def br(matched):
    s = matched.group()
    len_s = len(s)
    if len_s < 4:
        return bold(s[:1]) + s[1:]
    elif 4 <= len_s < 8:
        return bold(s[:2]) + s[2:]
    elif 8 <= len_s:
        return bold(s[:3]) + s[3:]

def style(s, color, size):
    return f'<p style="color:{color};font-size:{size}pt">' + s + '</p>'

if __name__ == '__main__':
    br_text = re.sub('\w+', br, sys.stdin.read())
    styled_text = style(br_text, sys.argv[1], sys.argv[2])
    print(styled_text)
