#!/bin/bash

if [ "$#" -eq 1 ]; then
    result=`cp "$1" /tmp/demonstrating 2>&1`
    notify-send "[+] cp \"$1\" /tmp/demonstrating $result"
    exit
fi

line=`head -n1 /tmp/demonstrating`
for i in $(seq 1 ${#line}); do
    xdotool type --delay `shuf -i20-150 -n1` "${line:i-1:1}"
done

xdotool key Return
sed -i '1d' /tmp/demonstrating
